"""End-to-end: every fixture in fixtures/ is generated by oplx-tools,
handed to OmniPlan in the VM, opened, switched to Gantt View, exported
to PDF/PNG/CSV, and diffed against goldens stamped with the OmniPlan
version under test.

What each comparison catches:

- **CSV diff** — scheduler ground truth. A wrong dependency, a wrong
  kind, a wrong lead time, a missing/extra task — all change the
  scheduler's date math, which surfaces in the CSV. Locale-agnostic
  once dates are normalized.

- **PDF text diff (via pdftotext)** — outline content + effort labels
  + date headers. Catches WBS numbering errors, title escaping bugs,
  effort-format regressions, milestone-vs-task display.

- **PNG byte size** — a coarse sanity check that the gantt area
  rendered SOMETHING. Real pixel-diff against golden is the better
  test but requires per-OmniPlan-version golden bytes to be stable;
  byte-size-only is the floor.
"""

from __future__ import annotations

import importlib
import pkgutil
from pathlib import Path

import pytest

from oplx import generate

from . import fixtures as fixtures_pkg
from . import vm_helpers


def _discover_fixtures() -> list[tuple[str, object]]:
    """Find every `fixtures/fNN_*.py` module — each must expose NAME (str)
    and build() -> Project."""
    found: list[tuple[str, object]] = []
    for info in pkgutil.iter_modules(fixtures_pkg.__path__):
        if info.name.startswith("_"):
            continue
        mod = importlib.import_module(f"{fixtures_pkg.__name__}.{info.name}")
        if not hasattr(mod, "NAME") or not hasattr(mod, "build"):
            continue
        found.append((mod.NAME, mod))
    found.sort(key=lambda x: x[0])
    return found


FIXTURES = _discover_fixtures()


@pytest.mark.integration
@pytest.mark.parametrize(("name", "module"), FIXTURES, ids=[n for n, _ in FIXTURES])
def test_fixture_round_trips(
    name: str,
    module: object,
    tmp_path: Path,
    run_dir: Path,
    golden_dir: Path,
    update_goldens: bool,
) -> None:
    """Generate, push to VM, export, compare to goldens."""
    project = module.build()  # type: ignore[attr-defined]
    oplx_path = tmp_path / f"{name}.oplx"
    generate(project, oplx_path)

    artifacts = vm_helpers.run_fixture(
        name, oplx_path, work_dir=run_dir / name
    )

    csv_actual = vm_helpers.normalize_csv(artifacts.csv)
    pdf_actual = vm_helpers.pdf_to_text(artifacts.pdf)
    png_size = artifacts.png.stat().st_size

    golden_csv = golden_dir / f"{name}.csv.txt"
    golden_pdf = golden_dir / f"{name}.pdf.txt"
    golden_png_size = golden_dir / f"{name}.png.size"

    if update_goldens:
        golden_csv.write_text(csv_actual)
        golden_pdf.write_text(pdf_actual)
        golden_png_size.write_text(str(png_size))
        pytest.skip(f"UPDATE_GOLDENS=1 — wrote goldens for {name}")

    if not golden_csv.exists():
        pytest.skip(f"no golden for {name} — run with UPDATE_GOLDENS=1 to baseline")

    assert csv_actual == golden_csv.read_text(), (
        f"CSV diff for {name} — scheduler output changed. "
        f"If this is intentional, re-baseline with UPDATE_GOLDENS=1."
    )
    assert pdf_actual == golden_pdf.read_text(), (
        f"PDF text diff for {name} — outline/effort/date layout changed. "
        f"If this is intentional, re-baseline with UPDATE_GOLDENS=1."
    )
    expected_png = int(golden_png_size.read_text())
    # PNG byte-size tolerance: ±10% — exact equality is too brittle across
    # OmniPlan minor versions, but a 50% size change usually means the
    # gantt area rendered empty or duplicated.
    low, high = int(expected_png * 0.9), int(expected_png * 1.1)
    assert low <= png_size <= high, (
        f"PNG size for {name} is {png_size} bytes, expected ~{expected_png} "
        f"(±10%). Re-baseline with UPDATE_GOLDENS=1 if intentional."
    )
